function e(a){throw a;}var aa=void 0,h=!0,k=null,l=!1;function ba(){return function(a){return a}}function n(a){return function(){return this[a]}}function q(a){return function(){return a}}var r,ca=this;function da(a,b){var c=a.split("."),d=ca;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==aa?d[f]=b:d=d[f]?d[f]:d[f]={}}
function s(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){return"string"==typeof a}var fa="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ga=0;function ha(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};function ia(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();"undefined"==typeof d&&e(Error("[goog.string.format] Template required"));return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,j,m,p,v,x){if("%"==p)return"%";var z=c.shift();"undefined"==typeof z&&e(Error("[goog.string.format] Not enough arguments"));arguments[0]=z;return ia.aa[p].apply(k,arguments)})}ia.aa={};
ia.aa.s=function(a,b,c){return isNaN(c)||""==c||a.length>=c?a:a=-1<b.indexOf("-",0)?a+Array(c-a.length+1).join(" "):Array(c-a.length+1).join(" ")+a};
ia.aa.f=function(a,b,c,d,f){d=a.toString();isNaN(f)||""==f||(d=a.toFixed(f));var g;g=0>a?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=a&&(d=g+d);if(isNaN(c)||d.length>=c)return d;d=isNaN(f)?Math.abs(a).toString():Math.abs(a).toFixed(f);a=c-d.length-g.length;return d=0<=b.indexOf("-",0)?g+d+Array(a+1).join(" "):g+Array(a+1).join(0<=b.indexOf("0",0)?"0":" ")+d};ia.aa.d=function(a,b,c,d,f,g,i,j){return ia.aa.f(parseInt(a,10),b,c,d,0,g,i,j)};ia.aa.i=ia.aa.d;ia.aa.u=ia.aa.d;function ja(a,b){a!=k&&this.append.apply(this,arguments)}ja.prototype.sa="";ja.prototype.append=function(a,b,c){this.sa+=a;if(b!=k)for(var d=1;d<arguments.length;d++)this.sa+=arguments[d];return this};ja.prototype.toString=n("sa");da("cljs.core.set_print_fn_BANG_",ba());function ka(){return ma(["\ufdd0:flush-on-newline",h,"\ufdd0:readably",h,"\ufdd0:meta",l,"\ufdd0:dup",l])}function t(a){return a!=k&&a!==l}function na(a){var b=ea(a);return b?"\ufdd0"!==a.charAt(0):b}function u(a,b){return a[s(b==k?k:b)]?h:a._?h:l}function w(a,b){var c=b==k?k:b.constructor,c=t(t(c)?c.ib:c)?c.vb:s(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}var oa={},pa={};
function y(a){if(a?a.L:a)return a.L(a);var b;var c=y[s(a==k?k:a)];c?b=c:(c=y._)?b=c:e(w("ICounted.-count",a));return b.call(k,a)}function qa(a,b){if(a?a.A:a)return a.A(a,b);var c;var d=qa[s(a==k?k:a)];d?c=d:(d=qa._)?c=d:e(w("ICollection.-conj",a));return c.call(k,a,b)}var ra={},A,sa=k;function ta(a,b){if(a?a.D:a)return a.D(a,b);var c;var d=A[s(a==k?k:a)];d?c=d:(d=A._)?c=d:e(w("IIndexed.-nth",a));return c.call(k,a,b)}
function ua(a,b,c){if(a?a.U:a)return a.U(a,b,c);var d;var f=A[s(a==k?k:a)];f?d=f:(f=A._)?d=f:e(w("IIndexed.-nth",a));return d.call(k,a,b,c)}sa=function(a,b,c){switch(arguments.length){case 2:return ta.call(this,a,b);case 3:return ua.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};sa.a=ta;sa.c=ua;A=sa;var va={};function B(a){if(a?a.M:a)return a.M(a);var b;var c=B[s(a==k?k:a)];c?b=c:(c=B._)?b=c:e(w("ISeq.-first",a));return b.call(k,a)}
function C(a){if(a?a.N:a)return a.N(a);var b;var c=C[s(a==k?k:a)];c?b=c:(c=C._)?b=c:e(w("ISeq.-rest",a));return b.call(k,a)}var wa={},xa,ya=k;function za(a,b){if(a?a.V:a)return a.V(a,b);var c;var d=xa[s(a==k?k:a)];d?c=d:(d=xa._)?c=d:e(w("ILookup.-lookup",a));return c.call(k,a,b)}function Aa(a,b,c){if(a?a.H:a)return a.H(a,b,c);var d;var f=xa[s(a==k?k:a)];f?d=f:(f=xa._)?d=f:e(w("ILookup.-lookup",a));return d.call(k,a,b,c)}
ya=function(a,b,c){switch(arguments.length){case 2:return za.call(this,a,b);case 3:return Aa.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};ya.a=za;ya.c=Aa;xa=ya;function Ba(a,b,c){if(a?a.ja:a)return a.ja(a,b,c);var d;var f=Ba[s(a==k?k:a)];f?d=f:(f=Ba._)?d=f:e(w("IAssociative.-assoc",a));return d.call(k,a,b,c)}var Ca={},Da={};function Ea(a){if(a?a.Va:a)return a.Va(a);var b;var c=Ea[s(a==k?k:a)];c?b=c:(c=Ea._)?b=c:e(w("IMapEntry.-key",a));return b.call(k,a)}
function Ga(a){if(a?a.Wa:a)return a.Wa(a);var b;var c=Ga[s(a==k?k:a)];c?b=c:(c=Ga._)?b=c:e(w("IMapEntry.-val",a));return b.call(k,a)}var Ha={};function Ia(a){if(a?a.bb:a)return a.state;var b;var c=Ia[s(a==k?k:a)];c?b=c:(c=Ia._)?b=c:e(w("IDeref.-deref",a));return b.call(k,a)}var Ja={};function Ka(a){if(a?a.I:a)return a.I(a);var b;var c=Ka[s(a==k?k:a)];c?b=c:(c=Ka._)?b=c:e(w("IMeta.-meta",a));return b.call(k,a)}
function La(a,b){if(a?a.K:a)return a.K(a,b);var c;var d=La[s(a==k?k:a)];d?c=d:(d=La._)?c=d:e(w("IWithMeta.-with-meta",a));return c.call(k,a,b)}var Ma={},Na,Oa=k;function Pa(a,b){if(a?a.la:a)return a.la(a,b);var c;var d=Na[s(a==k?k:a)];d?c=d:(d=Na._)?c=d:e(w("IReduce.-reduce",a));return c.call(k,a,b)}function Qa(a,b,c){if(a?a.ma:a)return a.ma(a,b,c);var d;var f=Na[s(a==k?k:a)];f?d=f:(f=Na._)?d=f:e(w("IReduce.-reduce",a));return d.call(k,a,b,c)}
Oa=function(a,b,c){switch(arguments.length){case 2:return Pa.call(this,a,b);case 3:return Qa.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};Oa.a=Pa;Oa.c=Qa;Na=Oa;function Ra(a,b){if(a?a.w:a)return a.w(a,b);var c;var d=Ra[s(a==k?k:a)];d?c=d:(d=Ra._)?c=d:e(w("IEquiv.-equiv",a));return c.call(k,a,b)}function Sa(a){if(a?a.C:a)return a.C(a);var b;var c=Sa[s(a==k?k:a)];c?b=c:(c=Sa._)?b=c:e(w("IHash.-hash",a));return b.call(k,a)}
function Ta(a){if(a?a.G:a)return a.G(a);var b;var c=Ta[s(a==k?k:a)];c?b=c:(c=Ta._)?b=c:e(w("ISeqable.-seq",a));return b.call(k,a)}var Ua={};function D(a,b){if(a?a.Ya:a)return a.Ya(0,b);var c;var d=D[s(a==k?k:a)];d?c=d:(d=D._)?c=d:e(w("IWriter.-write",a));return c.call(k,a,b)}function Va(a){if(a?a.hb:a)return k;var b;var c=Va[s(a==k?k:a)];c?b=c:(c=Va._)?b=c:e(w("IWriter.-flush",a));return b.call(k,a)}var Wa={};
function Xa(a,b,c){if(a?a.z:a)return a.z(a,b,c);var d;var f=Xa[s(a==k?k:a)];f?d=f:(f=Xa._)?d=f:e(w("IPrintWithWriter.-pr-writer",a));return d.call(k,a,b,c)}function Ya(a,b,c){if(a?a.Xa:a)return a.Xa(a,b,c);var d;var f=Ya[s(a==k?k:a)];f?d=f:(f=Ya._)?d=f:e(w("IWatchable.-notify-watches",a));return d.call(k,a,b,c)}function Za(a){if(a?a.ya:a)return a.ya(a);var b;var c=Za[s(a==k?k:a)];c?b=c:(c=Za._)?b=c:e(w("IEditableCollection.-as-transient",a));return b.call(k,a)}
function $a(a,b){if(a?a.ta:a)return a.ta(a,b);var c;var d=$a[s(a==k?k:a)];d?c=d:(d=$a._)?c=d:e(w("ITransientCollection.-conj!",a));return c.call(k,a,b)}function ab(a){if(a?a.za:a)return a.za(a);var b;var c=ab[s(a==k?k:a)];c?b=c:(c=ab._)?b=c:e(w("ITransientCollection.-persistent!",a));return b.call(k,a)}function bb(a,b,c){if(a?a.na:a)return a.na(a,b,c);var d;var f=bb[s(a==k?k:a)];f?d=f:(f=bb._)?d=f:e(w("ITransientAssociative.-assoc!",a));return d.call(k,a,b,c)}
function cb(a){if(a?a.Sa:a)return a.Sa();var b;var c=cb[s(a==k?k:a)];c?b=c:(c=cb._)?b=c:e(w("IChunk.-drop-first",a));return b.call(k,a)}function db(a){if(a?a.Ba:a)return a.Ba(a);var b;var c=db[s(a==k?k:a)];c?b=c:(c=db._)?b=c:e(w("IChunkedSeq.-chunked-first",a));return b.call(k,a)}function eb(a){if(a?a.xa:a)return a.xa(a);var b;var c=eb[s(a==k?k:a)];c?b=c:(c=eb._)?b=c:e(w("IChunkedSeq.-chunked-rest",a));return b.call(k,a)}function fb(a){this.jb=a;this.r=0;this.j=1073741824}
fb.prototype.Ya=function(a,b){return this.jb.append(b)};fb.prototype.hb=q(k);function gb(a){var b=new ja,c=new fb(b);a.z(a,c,ka());Va(c);return""+E(b)}function G(a,b,c,d,f){this.qa=a;this.name=b;this.ia=c;this.wa=d;this.ra=f;this.j=2154168321;this.r=4096}G.prototype.z=function(a,b){return D(b,this.ia)};
G.prototype.C=function(){-1===this.wa&&(this.wa=hb.a?hb.a(H.e?H.e(this.qa):H.call(k,this.qa),H.e?H.e(this.name):H.call(k,this.name)):hb.call(k,H.e?H.e(this.qa):H.call(k,this.qa),H.e?H.e(this.name):H.call(k,this.name)));return this.wa};G.prototype.K=function(a,b){return new G(this.qa,this.name,this.ia,this.wa,b)};G.prototype.I=n("ra");var ib=k,ib=function(a,b,c){switch(arguments.length){case 2:return xa.c(b,this,k);case 3:return xa.c(b,this,c)}e(Error("Invalid arity: "+arguments.length))};
G.prototype.call=ib;G.prototype.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};G.prototype.w=function(a,b){return b instanceof G?this.ia===b.ia:l};G.prototype.toString=n("ia");function I(a){if(a==k)return k;var b;if(b=a)b=(b=a.j&8388608)?b:a.rb;if(b)return a.G(a);if(a instanceof Array||na(a))return 0===a.length?k:new jb(a,0);if(u(wa,a))return Ta(a);e(Error([E(a),E("is not ISeqable")].join("")))}
function J(a){if(a==k)return k;var b;if(b=a)b=(b=a.j&64)?b:a.Qa;if(b)return a.M(a);a=I(a);return a==k?k:B(a)}function L(a){if(a!=k){var b;if(b=a)b=(b=a.j&64)?b:a.Qa;if(b)return a.N(a);a=I(a);return a!=k?C(a):kb}return kb}function M(a){if(a==k)a=k;else{var b;if(b=a)b=(b=a.j&128)?b:a.qb;a=b?a.da(a):I(L(a))}return a}var lb,mb=k;function nb(a,b){var c=a===b;return c?c:Ra(a,b)}function ob(a,b,c){for(;;)if(t(mb.a(a,b)))if(M(c))a=b,b=J(c),c=M(c);else return mb.a(b,J(c));else return l}
function pb(a,b,c){var d=k;2<arguments.length&&(d=N(Array.prototype.slice.call(arguments,2),0));return ob.call(this,a,b,d)}pb.o=2;pb.k=function(a){var b=J(a),a=M(a),c=J(a),a=L(a);return ob(b,c,a)};pb.g=ob;mb=function(a,b,c){switch(arguments.length){case 1:return h;case 2:return nb.call(this,a,b);default:return pb.g(a,b,N(arguments,2))}e(Error("Invalid arity: "+arguments.length))};mb.o=2;mb.k=pb.k;mb.e=q(h);mb.a=nb;mb.g=pb.g;lb=mb;Sa["null"]=q(0);pa["null"]=h;y["null"]=q(0);
Ra["null"]=function(a,b){return b==k};La["null"]=q(k);Ja["null"]=h;Ka["null"]=q(k);Ca["null"]=h;Date.prototype.w=function(a,b){var c=b instanceof Date;return c?a.toString()===b.toString():c};Sa.number=function(a){return Math.floor(a)%2147483647};Ra.number=function(a,b){return a===b};Sa["boolean"]=function(a){return a===h?1:0};Ja["function"]=h;Ka["function"]=q(k);oa["function"]=h;Sa._=function(a){return a[fa]||(a[fa]=++ga)};var qb,rb=k;
function sb(a,b){var c=y(a);if(0===c)return b.B?b.B():b.call(k);for(var d=A.a(a,0),f=1;;)if(f<c)d=b.a?b.a(d,A.a(a,f)):b.call(k,d,A.a(a,f)),f+=1;else return d}function tb(a,b,c){for(var d=y(a),f=0;;)if(f<d)c=b.a?b.a(c,A.a(a,f)):b.call(k,c,A.a(a,f)),f+=1;else return c}function ub(a,b,c,d){for(var f=y(a);;)if(d<f)c=b.a?b.a(c,A.a(a,d)):b.call(k,c,A.a(a,d)),d+=1;else return c}
rb=function(a,b,c,d){switch(arguments.length){case 2:return sb.call(this,a,b);case 3:return tb.call(this,a,b,c);case 4:return ub.call(this,a,b,c,d)}e(Error("Invalid arity: "+arguments.length))};rb.a=sb;rb.c=tb;rb.l=ub;qb=rb;var vb,wb=k;function xb(a,b){var c=a.length;if(0===a.length)return b.B?b.B():b.call(k);for(var d=a[0],f=1;;)if(f<c)d=b.a?b.a(d,a[f]):b.call(k,d,a[f]),f+=1;else return d}function yb(a,b,c){for(var d=a.length,f=0;;)if(f<d)c=b.a?b.a(c,a[f]):b.call(k,c,a[f]),f+=1;else return c}
function zb(a,b,c,d){for(var f=a.length;;)if(d<f)c=b.a?b.a(c,a[d]):b.call(k,c,a[d]),d+=1;else return c}wb=function(a,b,c,d){switch(arguments.length){case 2:return xb.call(this,a,b);case 3:return yb.call(this,a,b,c);case 4:return zb.call(this,a,b,c,d)}e(Error("Invalid arity: "+arguments.length))};wb.a=xb;wb.c=yb;wb.l=zb;vb=wb;function Ab(a){if(a)var b=a.j&2,a=(b?b:a.nb)?h:a.j?l:u(pa,a);else a=u(pa,a);return a}function Bb(a){if(a)var b=a.j&16,a=(b?b:a.Ua)?h:a.j?l:u(ra,a);else a=u(ra,a);return a}
function jb(a,b){this.b=a;this.m=b;this.r=0;this.j=166199550}r=jb.prototype;r.C=function(a){return Cb.e?Cb.e(a):Cb.call(k,a)};r.da=function(){return this.m+1<this.b.length?new jb(this.b,this.m+1):k};r.A=function(a,b){return P.a?P.a(b,a):P.call(k,b,a)};r.toString=function(){return gb(this)};r.la=function(a,b){return vb.l(this.b,b,this.b[this.m],this.m+1)};r.ma=function(a,b,c){return vb.l(this.b,b,c,this.m)};r.G=ba();r.L=function(){return this.b.length-this.m};r.M=function(){return this.b[this.m]};
r.N=function(){return this.m+1<this.b.length?new jb(this.b,this.m+1):Db.B?Db.B():Db.call(k)};r.w=function(a,b){return Eb.a?Eb.a(a,b):Eb.call(k,a,b)};r.D=function(a,b){var c=b+this.m;return c<this.b.length?this.b[c]:k};r.U=function(a,b,c){a=b+this.m;return a<this.b.length?this.b[a]:c};var Fb,Gb=k;function Hb(a){return Gb.a(a,0)}function Ib(a,b){return b<a.length?new jb(a,b):k}
Gb=function(a,b){switch(arguments.length){case 1:return Hb.call(this,a);case 2:return Ib.call(this,a,b)}e(Error("Invalid arity: "+arguments.length))};Gb.e=Hb;Gb.a=Ib;Fb=Gb;var N,Jb=k;function Kb(a){return Fb.a(a,0)}function Lb(a,b){return Fb.a(a,b)}Jb=function(a,b){switch(arguments.length){case 1:return Kb.call(this,a);case 2:return Lb.call(this,a,b)}e(Error("Invalid arity: "+arguments.length))};Jb.e=Kb;Jb.a=Lb;N=Jb;Ma.array=h;Na.array=function(a,b){return vb.a(a,b)};
Na.array=function(a,b,c){return vb.c(a,b,c)};pa.array=h;y.array=function(a){return a.length};Ra._=function(a,b){return a===b};var Mb,Nb=k;function Ob(a,b){return a!=k?qa(a,b):Db.e?Db.e(b):Db.call(k,b)}function Pb(a,b,c){for(;;)if(t(c))a=Nb.a(a,b),b=J(c),c=M(c);else return Nb.a(a,b)}function Qb(a,b,c){var d=k;2<arguments.length&&(d=N(Array.prototype.slice.call(arguments,2),0));return Pb.call(this,a,b,d)}Qb.o=2;Qb.k=function(a){var b=J(a),a=M(a),c=J(a),a=L(a);return Pb(b,c,a)};Qb.g=Pb;
Nb=function(a,b,c){switch(arguments.length){case 2:return Ob.call(this,a,b);default:return Qb.g(a,b,N(arguments,2))}e(Error("Invalid arity: "+arguments.length))};Nb.o=2;Nb.k=Qb.k;Nb.a=Ob;Nb.g=Qb.g;Mb=Nb;function Rb(a){if(Ab(a))a=y(a);else a:{for(var a=I(a),b=0;;){if(Ab(a)){a=b+y(a);break a}a=M(a);b+=1}a=aa}return a}var Sb,Tb=k;
function Ub(a,b){for(;;){a==k&&e(Error("Index out of bounds"));if(0===b){if(I(a))return J(a);e(Error("Index out of bounds"))}if(Bb(a))return A.a(a,b);if(I(a))var c=M(a),d=b-1,a=c,b=d;else e(Error("Index out of bounds"))}}function Vb(a,b,c){for(;;){if(a==k)return c;if(0===b)return I(a)?J(a):c;if(Bb(a))return A.c(a,b,c);if(I(a))a=M(a),b-=1;else return c}}Tb=function(a,b,c){switch(arguments.length){case 2:return Ub.call(this,a,b);case 3:return Vb.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};
Tb.a=Ub;Tb.c=Vb;Sb=Tb;var Wb,Xb=k;function Yb(a,b){var c;if(a==k)c=k;else{if(c=a)c=(c=a.j&16)?c:a.Ua;c=c?a.D(a,Math.floor(b)):a instanceof Array?b<a.length?a[b]:k:na(a)?b<a.length?a[b]:k:Sb.a(a,Math.floor(b))}return c}function Zb(a,b,c){if(a!=k){var d;if(d=a)d=(d=a.j&16)?d:a.Ua;a=d?a.U(a,Math.floor(b),c):a instanceof Array?b<a.length?a[b]:c:na(a)?b<a.length?a[b]:c:Sb.c(a,Math.floor(b),c)}else a=c;return a}
Xb=function(a,b,c){switch(arguments.length){case 2:return Yb.call(this,a,b);case 3:return Zb.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};Xb.a=Yb;Xb.c=Zb;Wb=Xb;var Q,ac=k;function bc(a,b){var c;if(a==k)c=k;else{if(c=a)c=(c=a.j&256)?c:a.Pa;c=c?a.V(a,b):a instanceof Array?b<a.length?a[b]:k:na(a)?b<a.length?a[b]:k:u(wa,a)?xa.a(a,b):k}return c}
function cc(a,b,c){if(a!=k){var d;if(d=a)d=(d=a.j&256)?d:a.Pa;a=d?a.H(a,b,c):a instanceof Array?b<a.length?a[b]:c:na(a)?b<a.length?a[b]:c:u(wa,a)?xa.c(a,b,c):c}else a=c;return a}ac=function(a,b,c){switch(arguments.length){case 2:return bc.call(this,a,b);case 3:return cc.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};ac.a=bc;ac.c=cc;Q=ac;var dc,ec=k;function fc(a,b,c){return a!=k?Ba(a,b,c):gc.a?gc.a(b,c):gc.call(k,b,c)}
function hc(a,b,c,d){for(;;)if(a=ec.c(a,b,c),t(d))b=J(d),c=J(M(d)),d=M(M(d));else return a}function ic(a,b,c,d){var f=k;3<arguments.length&&(f=N(Array.prototype.slice.call(arguments,3),0));return hc.call(this,a,b,c,f)}ic.o=3;ic.k=function(a){var b=J(a),a=M(a),c=J(a),a=M(a),d=J(a),a=L(a);return hc(b,c,d,a)};ic.g=hc;ec=function(a,b,c,d){switch(arguments.length){case 3:return fc.call(this,a,b,c);default:return ic.g(a,b,c,N(arguments,3))}e(Error("Invalid arity: "+arguments.length))};ec.o=3;ec.k=ic.k;
ec.c=fc;ec.g=ic.g;dc=ec;function jc(a){var b;b=a?((b=a.j&131072)?b:a.eb)||(a.j?0:u(Ja,a)):u(Ja,a);return b?Ka(a):k}var kc={},lc=0,H,mc=k;function nc(a){return mc.a(a,h)}function oc(a,b){var c=ea(a);(c?b:c)?(255<lc&&(kc={},lc=0),c=kc[a],"number"!==typeof c&&(c=ha(a),kc[a]=c,lc+=1)):c=Sa(a);return c}mc=function(a,b){switch(arguments.length){case 1:return nc.call(this,a);case 2:return oc.call(this,a,b)}e(Error("Invalid arity: "+arguments.length))};mc.e=nc;mc.a=oc;H=mc;
function pc(a){if(a)var b=a.j&16384,a=(b?b:a.tb)?h:a.j?l:u(Ha,a);else a=u(Ha,a);return a}function qc(a){var b=a instanceof rc;return b?b:a instanceof sc}function tc(a,b,c,d,f){for(;0!==f;)c[d]=a[b],d+=1,f-=1,b+=1}function uc(a){if(a==k)a=l;else if(a)var b=a.j&64,a=(b?b:a.Qa)?h:a.j?l:u(va,a);else a=u(va,a);return a}function vc(a){var b=ea(a);return b?"\ufdd0"===a.charAt(0):b}
function wc(a,b){if(a===b)return 0;if(a==k)return-1;if(b==k)return 1;if((a==k?k:a.constructor)===(b==k?k:b.constructor)){var c;if(c=a)c=(c=a.r&2048)?c:a.$a;return c?a.ab(a,b):a>b?1:a<b?-1:0}e(Error("compare on non-nil objects of different types"))}var xc,yc=k;function zc(a,b){var c=Rb(a),d=Rb(b);return c<d?-1:c>d?1:yc.l(a,b,c,0)}function Ac(a,b,c,d){for(;;){var f=wc(Wb.a(a,d),Wb.a(b,d)),g=0===f;if(g?d+1<c:g)d+=1;else return f}}
yc=function(a,b,c,d){switch(arguments.length){case 2:return zc.call(this,a,b);case 4:return Ac.call(this,a,b,c,d)}e(Error("Invalid arity: "+arguments.length))};yc.a=zc;yc.l=Ac;xc=yc;var Bc,Cc=k;function Dc(a,b){var c=I(b);return c?Ec.c?Ec.c(a,J(c),M(c)):Ec.call(k,a,J(c),M(c)):a.B?a.B():a.call(k)}function Fc(a,b,c){for(c=I(c);;)if(c)b=a.a?a.a(b,J(c)):a.call(k,b,J(c)),c=M(c);else return b}
Cc=function(a,b,c){switch(arguments.length){case 2:return Dc.call(this,a,b);case 3:return Fc.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};Cc.a=Dc;Cc.c=Fc;Bc=Cc;var Ec,Gc=k;function Hc(a,b){var c;if(c=b)c=(c=b.j&524288)?c:b.gb;return c?b.la(b,a):b instanceof Array?vb.a(b,a):na(b)?vb.a(b,a):u(Ma,b)?Na.a(b,a):Bc.a(a,b)}function Ic(a,b,c){var d;if(d=c)d=(d=c.j&524288)?d:c.gb;return d?c.ma(c,a,b):c instanceof Array?vb.c(c,a,b):na(c)?vb.c(c,a,b):u(Ma,c)?Na.c(c,a,b):Bc.c(a,b,c)}
Gc=function(a,b,c){switch(arguments.length){case 2:return Hc.call(this,a,b);case 3:return Ic.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};Gc.a=Hc;Gc.c=Ic;Ec=Gc;var Jc,Kc=k;function Lc(a,b,c){return Ec.c(Kc,a+b,c)}function Mc(a,b,c){var d=k;2<arguments.length&&(d=N(Array.prototype.slice.call(arguments,2),0));return Lc.call(this,a,b,d)}Mc.o=2;Mc.k=function(a){var b=J(a),a=M(a),c=J(a),a=L(a);return Lc(b,c,a)};Mc.g=Lc;
Kc=function(a,b,c){switch(arguments.length){case 0:return 0;case 1:return a;case 2:return a+b;default:return Mc.g(a,b,N(arguments,2))}e(Error("Invalid arity: "+arguments.length))};Kc.o=2;Kc.k=Mc.k;Kc.B=q(0);Kc.e=ba();Kc.a=function(a,b){return a+b};Kc.g=Mc.g;Jc=Kc;var Nc,Oc=k;function Pc(a,b,c){return Ec.c(Oc,a*b,c)}function Qc(a,b,c){var d=k;2<arguments.length&&(d=N(Array.prototype.slice.call(arguments,2),0));return Pc.call(this,a,b,d)}Qc.o=2;
Qc.k=function(a){var b=J(a),a=M(a),c=J(a),a=L(a);return Pc(b,c,a)};Qc.g=Pc;Oc=function(a,b,c){switch(arguments.length){case 0:return 1;case 1:return a;case 2:return a*b;default:return Qc.g(a,b,N(arguments,2))}e(Error("Invalid arity: "+arguments.length))};Oc.o=2;Oc.k=Qc.k;Oc.B=q(1);Oc.e=ba();Oc.a=function(a,b){return a*b};Oc.g=Qc.g;Nc=Oc;function Rc(a){return 0<=a?Math.floor.e?Math.floor.e(a):Math.floor.call(k,a):Math.ceil.e?Math.ceil.e(a):Math.ceil.call(k,a)}
function Sc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}function Tc(a){for(var b=1,a=I(a);;){var c=a;if(t(c?0<b:c))b-=1,a=M(a);else return a}}var Uc,Vc=k;function Wc(a){return a==k?"":a.toString()}function Xc(a,b){return function(a,b){for(;;)if(t(b))var f=a.append(Vc.e(J(b))),g=M(b),a=f,b=g;else return Vc.e(a)}.call(k,new ja(Vc.e(a)),b)}
function Yc(a,b){var c=k;1<arguments.length&&(c=N(Array.prototype.slice.call(arguments,1),0));return Xc.call(this,a,c)}Yc.o=1;Yc.k=function(a){var b=J(a),a=L(a);return Xc(b,a)};Yc.g=Xc;Vc=function(a,b){switch(arguments.length){case 0:return"";case 1:return Wc.call(this,a);default:return Yc.g(a,N(arguments,1))}e(Error("Invalid arity: "+arguments.length))};Vc.o=1;Vc.k=Yc.k;Vc.B=q("");Vc.e=Wc;Vc.g=Yc.g;Uc=Vc;var E,Zc=k;
function $c(a){return vc(a)?Uc.g(":",N([a.substring(2,a.length)],0)):a==k?"":a.toString()}function ad(a,b){return function(a,b){for(;;)if(t(b))var f=a.append(Zc.e(J(b))),g=M(b),a=f,b=g;else return Uc.e(a)}.call(k,new ja(Zc.e(a)),b)}function bd(a,b){var c=k;1<arguments.length&&(c=N(Array.prototype.slice.call(arguments,1),0));return ad.call(this,a,c)}bd.o=1;bd.k=function(a){var b=J(a),a=L(a);return ad(b,a)};bd.g=ad;
Zc=function(a,b){switch(arguments.length){case 0:return"";case 1:return $c.call(this,a);default:return bd.g(a,N(arguments,1))}e(Error("Invalid arity: "+arguments.length))};Zc.o=1;Zc.k=bd.k;Zc.B=q("");Zc.e=$c;Zc.g=bd.g;E=Zc;var cd,dd=k,dd=function(a,b,c){switch(arguments.length){case 2:return a.substring(b);case 3:return a.substring(b,c)}e(Error("Invalid arity: "+arguments.length))};dd.a=function(a,b){return a.substring(b)};dd.c=function(a,b,c){return a.substring(b,c)};cd=dd;
function Eb(a,b){var c;c=b?((c=b.j&16777216)?c:b.sb)||(b.j?0:u(Ua,b)):u(Ua,b);if(c)a:{c=I(a);for(var d=I(b);;){if(c==k){c=d==k;break a}if(d!=k&&lb.a(J(c),J(d)))c=M(c),d=M(d);else{c=l;break a}}c=aa}else c=k;return t(c)?h:l}function hb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function Cb(a){return Ec.c(function(a,c){return hb(a,H.a(c,l))},H.a(J(a),l),M(a))}
function ed(a){for(var b=0,a=I(a);;)if(a)var c=J(a),b=(b+(H.e(S.e?S.e(c):S.call(k,c))^H.e(T.e?T.e(c):T.call(k,c))))%4503599627370496,a=M(a);else return b}function fd(a,b,c,d,f){this.p=a;this.ua=b;this.ca=c;this.count=d;this.n=f;this.r=0;this.j=65937646}r=fd.prototype;r.C=function(a){var b=this.n;return b!=k?b:this.n=a=Cb(a)};r.da=function(){return 1===this.count?k:this.ca};r.A=function(a,b){return new fd(this.p,b,a,this.count+1,k)};r.toString=function(){return gb(this)};
r.la=function(a,b){return Bc.a(b,a)};r.ma=function(a,b,c){return Bc.c(b,c,a)};r.G=ba();r.L=n("count");r.M=n("ua");r.N=function(){return 1===this.count?kb:this.ca};r.w=function(a,b){return Eb(a,b)};r.K=function(a,b){return new fd(b,this.ua,this.ca,this.count,this.n)};r.I=n("p");function gd(a){this.p=a;this.r=0;this.j=65413326}r=gd.prototype;r.C=q(0);r.da=q(k);r.A=function(a,b){return new fd(this.p,b,k,1,k)};r.toString=function(){return gb(this)};r.G=q(k);r.L=q(0);r.M=q(k);r.N=function(){return kb};
r.w=function(a,b){return Eb(a,b)};r.K=function(a,b){return new gd(b)};r.I=n("p");var kb=new gd(k),Db;function hd(a){var b;if(a instanceof jb)b=a.b;else a:{for(b=[];;)if(a!=k)b.push(a.M(a)),a=a.da(a);else break a;b=aa}for(var a=b.length,c=kb;;)if(0<a)var d=a-1,c=c.A(c,b[a-1]),a=d;else return c}function id(a){var b=k;0<arguments.length&&(b=N(Array.prototype.slice.call(arguments,0),0));return hd.call(this,b)}id.o=0;id.k=function(a){a=I(a);return hd(a)};id.g=hd;Db=id;
function jd(a,b,c,d){this.p=a;this.ua=b;this.ca=c;this.n=d;this.r=0;this.j=65405164}r=jd.prototype;r.C=function(a){var b=this.n;return b!=k?b:this.n=a=Cb(a)};r.da=function(){return this.ca==k?k:Ta(this.ca)};r.A=function(a,b){return new jd(k,b,a,this.n)};r.toString=function(){return gb(this)};r.G=ba();r.M=n("ua");r.N=function(){return this.ca==k?kb:this.ca};r.w=function(a,b){return Eb(a,b)};r.K=function(a,b){return new jd(b,this.ua,this.ca,this.n)};r.I=n("p");
function P(a,b){var c=b==k;if(!c&&(c=b))c=(c=b.j&64)?c:b.Qa;return c?new jd(k,a,b,k):new jd(k,a,I(b),k)}pa.string=h;y.string=function(a){return a.length};Sa.string=function(a){return ha(a)};function kd(a){this.Za=a;this.r=0;this.j=1}
var ld=k,ld=function(a,b,c){switch(arguments.length){case 2:var d=a,d=this;if(b==k)d=k;else{var f;f=b?((f=b.j&256)?f:b.Pa)||(b.j?0:u(wa,b)):u(wa,b);d=f?xa.c(b,d.Za,k):k}return d;case 3:return d=a,d=this,b==k?d=c:(f=b?((f=b.j&256)?f:b.Pa)||(b.j?0:u(wa,b)):u(wa,b),d=f?xa.c(b,d.Za,c):k),d}e(Error("Invalid arity: "+arguments.length))};kd.prototype.call=ld;kd.prototype.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};
var md=k,md=function(a,b,c){switch(arguments.length){case 2:return Q.a(b,this.toString());case 3:return Q.c(b,this.toString(),c)}e(Error("Invalid arity: "+arguments.length))};String.prototype.call=md;String.prototype.apply=function(a,b){return a.call.apply(a,[a].concat(b.slice()))};String.prototype.apply=function(a,b){return 2>b.length?Q.a(b[0],a):Q.c(b[0],a,b[1])};function nd(a){var b=a.x;if(a.Ra)return b;a.x=b.B?b.B():b.call(k);a.Ra=h;return a.x}
function od(a,b,c,d){this.p=a;this.Ra=b;this.x=c;this.n=d;this.r=0;this.j=31850700}r=od.prototype;r.C=function(a){var b=this.n;return b!=k?b:this.n=a=Cb(a)};r.da=function(a){return Ta(a.N(a))};r.A=function(a,b){return P(b,a)};r.toString=function(){return gb(this)};r.G=function(a){return I(nd(a))};r.M=function(a){return J(nd(a))};r.N=function(a){return L(nd(a))};r.w=function(a,b){return Eb(a,b)};r.K=function(a,b){return new od(b,this.Ra,this.x,this.n)};r.I=n("p");
function pd(a,b){this.Aa=a;this.end=b;this.r=0;this.j=2}pd.prototype.L=n("end");pd.prototype.add=function(a){this.Aa[this.end]=a;return this.end+=1};pd.prototype.ga=function(){var a=new rd(this.Aa,0,this.end);this.Aa=k;return a};function rd(a,b,c){this.b=a;this.v=b;this.end=c;this.r=0;this.j=524306}r=rd.prototype;r.la=function(a,b){return vb.l(this.b,b,this.b[this.v],this.v+1)};r.ma=function(a,b,c){return vb.l(this.b,b,c,this.v)};
r.Sa=function(){this.v===this.end&&e(Error("-drop-first of empty chunk"));return new rd(this.b,this.v+1,this.end)};r.D=function(a,b){return this.b[this.v+b]};r.U=function(a,b,c){return((a=0<=b)?b<this.end-this.v:a)?this.b[this.v+b]:c};r.L=function(){return this.end-this.v};var sd,td=k;function ud(a){return new rd(a,0,a.length)}function vd(a,b){return new rd(a,b,a.length)}function wd(a,b,c){return new rd(a,b,c)}
td=function(a,b,c){switch(arguments.length){case 1:return ud.call(this,a);case 2:return vd.call(this,a,b);case 3:return wd.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};td.e=ud;td.a=vd;td.c=wd;sd=td;function rc(a,b,c,d){this.ga=a;this.fa=b;this.p=c;this.n=d;this.j=31850604;this.r=1536}r=rc.prototype;r.C=function(a){var b=this.n;return b!=k?b:this.n=a=Cb(a)};r.A=function(a,b){return P(b,a)};r.toString=function(){return gb(this)};r.G=ba();r.M=function(){return A.a(this.ga,0)};
r.N=function(){return 1<y(this.ga)?new rc(cb(this.ga),this.fa,this.p,k):this.fa==k?kb:this.fa};r.Ta=function(){return this.fa==k?k:this.fa};r.w=function(a,b){return Eb(a,b)};r.K=function(a,b){return new rc(this.ga,this.fa,b,this.n)};r.I=n("p");r.Ba=n("ga");r.xa=function(){return this.fa==k?kb:this.fa};function xd(a,b){return 0===y(a)?b:new rc(a,b,k,k)}function yd(a){for(var b=[];;)if(I(a))b.push(J(a)),a=M(a);else return b}
function zd(a,b){if(Ab(a))return Rb(a);for(var c=a,d=b,f=0;;){var g;g=(g=0<d)?I(c):g;if(t(g))c=M(c),d-=1,f+=1;else return f}}var Bd=function Ad(b){return b==k?k:M(b)==k?I(J(b)):P(J(b),Ad(M(b)))},Cd,Dd=k;function Ed(){return new od(k,l,q(k),k)}function Fd(a){return new od(k,l,function(){return a},k)}function Gd(a,b){return new od(k,l,function(){var c=I(a);return c?qc(c)?xd(db(c),Dd.a(eb(c),b)):P(J(c),Dd.a(L(c),b)):b},k)}
function Hd(a,b,c){return function f(a,b){return new od(k,l,function(){var c=I(a);return c?qc(c)?xd(db(c),f(eb(c),b)):P(J(c),f(L(c),b)):t(b)?f(J(b),M(b)):k},k)}(Dd.a(a,b),c)}function Id(a,b,c){var d=k;2<arguments.length&&(d=N(Array.prototype.slice.call(arguments,2),0));return Hd.call(this,a,b,d)}Id.o=2;Id.k=function(a){var b=J(a),a=M(a),c=J(a),a=L(a);return Hd(b,c,a)};Id.g=Hd;
Dd=function(a,b,c){switch(arguments.length){case 0:return Ed.call(this);case 1:return Fd.call(this,a);case 2:return Gd.call(this,a,b);default:return Id.g(a,b,N(arguments,2))}e(Error("Invalid arity: "+arguments.length))};Dd.o=2;Dd.k=Id.k;Dd.B=Ed;Dd.e=Fd;Dd.a=Gd;Dd.g=Id.g;Cd=Dd;var Jd,Kd=k;function Ld(a,b,c){return P(a,P(b,c))}function Md(a,b,c,d){return P(a,P(b,P(c,d)))}function Nd(a,b,c,d,f){return P(a,P(b,P(c,P(d,Bd(f)))))}
function Od(a,b,c,d,f){var g=k;4<arguments.length&&(g=N(Array.prototype.slice.call(arguments,4),0));return Nd.call(this,a,b,c,d,g)}Od.o=4;Od.k=function(a){var b=J(a),a=M(a),c=J(a),a=M(a),d=J(a),a=M(a),f=J(a),a=L(a);return Nd(b,c,d,f,a)};Od.g=Nd;Kd=function(a,b,c,d,f){switch(arguments.length){case 1:return I(a);case 2:return P(a,b);case 3:return Ld.call(this,a,b,c);case 4:return Md.call(this,a,b,c,d);default:return Od.g(a,b,c,d,N(arguments,4))}e(Error("Invalid arity: "+arguments.length))};Kd.o=4;
Kd.k=Od.k;Kd.e=function(a){return I(a)};Kd.a=function(a,b){return P(a,b)};Kd.c=Ld;Kd.l=Md;Kd.g=Od.g;Jd=Kd;
function Pd(a,b,c){var d=I(c);if(0===b)return a.B?a.B():a.call(k);var c=B(d),f=C(d);if(1===b)return a.e?a.e(c):a.e?a.e(c):a.call(k,c);var d=B(f),g=C(f);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(k,c,d);var f=B(g),i=C(g);if(3===b)return a.c?a.c(c,d,f):a.c?a.c(c,d,f):a.call(k,c,d,f);var g=B(i),j=C(i);if(4===b)return a.l?a.l(c,d,f,g):a.l?a.l(c,d,f,g):a.call(k,c,d,f,g);i=B(j);j=C(j);if(5===b)return a.P?a.P(c,d,f,g,i):a.P?a.P(c,d,f,g,i):a.call(k,c,d,f,g,i);var a=B(j),m=C(j);if(6===b)return a.T?a.T(c,
d,f,g,i,a):a.T?a.T(c,d,f,g,i,a):a.call(k,c,d,f,g,i,a);var j=B(m),p=C(m);if(7===b)return a.ka?a.ka(c,d,f,g,i,a,j):a.ka?a.ka(c,d,f,g,i,a,j):a.call(k,c,d,f,g,i,a,j);var m=B(p),v=C(p);if(8===b)return a.Na?a.Na(c,d,f,g,i,a,j,m):a.Na?a.Na(c,d,f,g,i,a,j,m):a.call(k,c,d,f,g,i,a,j,m);var p=B(v),x=C(v);if(9===b)return a.Oa?a.Oa(c,d,f,g,i,a,j,m,p):a.Oa?a.Oa(c,d,f,g,i,a,j,m,p):a.call(k,c,d,f,g,i,a,j,m,p);var v=B(x),z=C(x);if(10===b)return a.Ca?a.Ca(c,d,f,g,i,a,j,m,p,v):a.Ca?a.Ca(c,d,f,g,i,a,j,m,p,v):a.call(k,
c,d,f,g,i,a,j,m,p,v);var x=B(z),F=C(z);if(11===b)return a.Da?a.Da(c,d,f,g,i,a,j,m,p,v,x):a.Da?a.Da(c,d,f,g,i,a,j,m,p,v,x):a.call(k,c,d,f,g,i,a,j,m,p,v,x);var z=B(F),K=C(F);if(12===b)return a.Ea?a.Ea(c,d,f,g,i,a,j,m,p,v,x,z):a.Ea?a.Ea(c,d,f,g,i,a,j,m,p,v,x,z):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z);var F=B(K),O=C(K);if(13===b)return a.Fa?a.Fa(c,d,f,g,i,a,j,m,p,v,x,z,F):a.Fa?a.Fa(c,d,f,g,i,a,j,m,p,v,x,z,F):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z,F);var K=B(O),R=C(O);if(14===b)return a.Ga?a.Ga(c,d,f,g,i,a,j,m,p,
v,x,z,F,K):a.Ga?a.Ga(c,d,f,g,i,a,j,m,p,v,x,z,F,K):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z,F,K);var O=B(R),X=C(R);if(15===b)return a.Ha?a.Ha(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O):a.Ha?a.Ha(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z,F,K,O);var R=B(X),la=C(X);if(16===b)return a.Ia?a.Ia(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R):a.Ia?a.Ia(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R);var X=B(la),Fa=C(la);if(17===b)return a.Ja?a.Ja(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X):a.Ja?a.Ja(c,
d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X);var la=B(Fa),$b=C(Fa);if(18===b)return a.Ka?a.Ka(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X,la):a.Ka?a.Ka(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X,la):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X,la);Fa=B($b);$b=C($b);if(19===b)return a.La?a.La(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X,la,Fa):a.La?a.La(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X,la,Fa):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X,la,Fa);var qd=B($b);C($b);if(20===b)return a.Ma?a.Ma(c,d,f,g,i,
a,j,m,p,v,x,z,F,K,O,R,X,la,Fa,qd):a.Ma?a.Ma(c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X,la,Fa,qd):a.call(k,c,d,f,g,i,a,j,m,p,v,x,z,F,K,O,R,X,la,Fa,qd);e(Error("Only up to 20 arguments supported on functions"))}var Qd,Rd=k;function Sd(a,b){var c=a.o;if(a.k){var d=zd(b,c+1);return d<=c?Pd(a,d,b):a.k(b)}return a.apply(a,yd(b))}function Td(a,b,c){b=Jd.a(b,c);c=a.o;if(a.k){var d=zd(b,c+1);return d<=c?Pd(a,d,b):a.k(b)}return a.apply(a,yd(b))}
function Ud(a,b,c,d){b=Jd.c(b,c,d);c=a.o;return a.k?(d=zd(b,c+1),d<=c?Pd(a,d,b):a.k(b)):a.apply(a,yd(b))}function Vd(a,b,c,d,f){b=Jd.l(b,c,d,f);c=a.o;return a.k?(d=zd(b,c+1),d<=c?Pd(a,d,b):a.k(b)):a.apply(a,yd(b))}function Wd(a,b,c,d,f,g){b=P(b,P(c,P(d,P(f,Bd(g)))));c=a.o;return a.k?(d=zd(b,c+1),d<=c?Pd(a,d,b):a.k(b)):a.apply(a,yd(b))}function Xd(a,b,c,d,f,g){var i=k;5<arguments.length&&(i=N(Array.prototype.slice.call(arguments,5),0));return Wd.call(this,a,b,c,d,f,i)}Xd.o=5;
Xd.k=function(a){var b=J(a),a=M(a),c=J(a),a=M(a),d=J(a),a=M(a),f=J(a),a=M(a),g=J(a),a=L(a);return Wd(b,c,d,f,g,a)};Xd.g=Wd;Rd=function(a,b,c,d,f,g){switch(arguments.length){case 2:return Sd.call(this,a,b);case 3:return Td.call(this,a,b,c);case 4:return Ud.call(this,a,b,c,d);case 5:return Vd.call(this,a,b,c,d,f);default:return Xd.g(a,b,c,d,f,N(arguments,5))}e(Error("Invalid arity: "+arguments.length))};Rd.o=5;Rd.k=Xd.k;Rd.a=Sd;Rd.c=Td;Rd.l=Ud;Rd.P=Vd;Rd.g=Xd.g;Qd=Rd;
function Yd(a,b){for(;;){if(I(b)==k)return h;if(t(a.e?a.e(J(b)):a.call(k,J(b))))var c=a,d=M(b),a=c,b=d;else return l}}function Zd(a){return a}var $d,U=k;function ae(a,b){return new od(k,l,function(){var c=I(b);if(c){if(qc(c)){for(var d=db(c),f=Rb(d),g=new pd(Array(f),0),i=0;;)if(i<f){var j=a.e?a.e(A.a(d,i)):a.call(k,A.a(d,i));g.add(j);i+=1}else break;return xd(g.ga(),U.a(a,eb(c)))}return P(a.e?a.e(J(c)):a.call(k,J(c)),U.a(a,L(c)))}return k},k)}
function be(a,b,c){return new od(k,l,function(){var d=I(b),f=I(c);return(d?f:d)?P(a.a?a.a(J(d),J(f)):a.call(k,J(d),J(f)),U.c(a,L(d),L(f))):k},k)}function ce(a,b,c,d){return new od(k,l,function(){var f=I(b),g=I(c),i=I(d);return(f?g?i:g:f)?P(a.c?a.c(J(f),J(g),J(i)):a.call(k,J(f),J(g),J(i)),U.l(a,L(f),L(g),L(i))):k},k)}
function de(a,b,c,d,f){return U.a(function(b){return Qd.a(a,b)},function i(a){return new od(k,l,function(){var b=U.a(I,a);return Yd(Zd,b)?P(U.a(J,b),i(U.a(L,b))):k},k)}(Mb.g(f,d,N([c,b],0))))}function ee(a,b,c,d,f){var g=k;4<arguments.length&&(g=N(Array.prototype.slice.call(arguments,4),0));return de.call(this,a,b,c,d,g)}ee.o=4;ee.k=function(a){var b=J(a),a=M(a),c=J(a),a=M(a),d=J(a),a=M(a),f=J(a),a=L(a);return de(b,c,d,f,a)};ee.g=de;
U=function(a,b,c,d,f){switch(arguments.length){case 2:return ae.call(this,a,b);case 3:return be.call(this,a,b,c);case 4:return ce.call(this,a,b,c,d);default:return ee.g(a,b,c,d,N(arguments,4))}e(Error("Invalid arity: "+arguments.length))};U.o=4;U.k=ee.k;U.a=ae;U.c=be;U.l=ce;U.g=ee.g;$d=U;var fe,V=k;function ge(a,b,c){var d=Wb.c(b,0,k),b=Tc(b);return t(b)?dc.c(a,d,V.c(Q.a(a,d),b,c)):dc.c(a,d,c.e?c.e(Q.a(a,d)):c.call(k,Q.a(a,d)))}
function he(a,b,c,d){var f=Wb.c(b,0,k),b=Tc(b);return t(b)?dc.c(a,f,V.l(Q.a(a,f),b,c,d)):dc.c(a,f,c.a?c.a(Q.a(a,f),d):c.call(k,Q.a(a,f),d))}function ie(a,b,c,d,f){var g=Wb.c(b,0,k),b=Tc(b);return t(b)?dc.c(a,g,V.P(Q.a(a,g),b,c,d,f)):dc.c(a,g,c.c?c.c(Q.a(a,g),d,f):c.call(k,Q.a(a,g),d,f))}function je(a,b,c,d,f,g){var i=Wb.c(b,0,k),b=Tc(b);return t(b)?dc.c(a,i,V.T(Q.a(a,i),b,c,d,f,g)):dc.c(a,i,c.l?c.l(Q.a(a,i),d,f,g):c.call(k,Q.a(a,i),d,f,g))}
function ke(a,b,c,d,f,g,i){var j=Wb.c(b,0,k),b=Tc(b);return t(b)?dc.c(a,j,Qd.g(V,Q.a(a,j),b,c,d,N([f,g,i],0))):dc.c(a,j,Qd.g(c,Q.a(a,j),d,f,g,N([i],0)))}function le(a,b,c,d,f,g,i){var j=k;6<arguments.length&&(j=N(Array.prototype.slice.call(arguments,6),0));return ke.call(this,a,b,c,d,f,g,j)}le.o=6;le.k=function(a){var b=J(a),a=M(a),c=J(a),a=M(a),d=J(a),a=M(a),f=J(a),a=M(a),g=J(a),a=M(a),i=J(a),a=L(a);return ke(b,c,d,f,g,i,a)};le.g=ke;
V=function(a,b,c,d,f,g,i){switch(arguments.length){case 3:return ge.call(this,a,b,c);case 4:return he.call(this,a,b,c,d);case 5:return ie.call(this,a,b,c,d,f);case 6:return je.call(this,a,b,c,d,f,g);default:return le.g(a,b,c,d,f,g,N(arguments,6))}e(Error("Invalid arity: "+arguments.length))};V.o=6;V.k=le.k;V.c=ge;V.l=he;V.P=ie;V.T=je;V.g=le.g;fe=V;function me(a,b){this.q=a;this.b=b}function ne(a){a=a.h;return 32>a?0:a-1>>>5<<5}
function oe(a,b,c){for(;;){if(0===b)return c;var d=new me(a,Array(32));d.b[0]=c;c=d;b-=5}}var qe=function pe(b,c,d,f){var g=new me(d.q,d.b.slice()),i=b.h-1>>>c&31;5===c?g.b[i]=f:(d=d.b[i],b=d!=k?pe(b,c-5,d,f):oe(k,c-5,f),g.b[i]=b);return g};function re(a,b){var c=0<=b;if(c?b<a.h:c){if(b>=ne(a))return a.F;for(var c=a.root,d=a.shift;;)if(0<d)var f=d-5,c=c.b[b>>>d&31],d=f;else return c.b}else c=a.h,e(Error([E("No item "),E(b),E(" in vector of length "),E(c)].join("")))}
var te=function se(b,c,d,f,g){var i=new me(d.q,d.b.slice());if(0===c)i.b[f&31]=g;else{var j=f>>>c&31,b=se(b,c-5,d.b[j],f,g);i.b[j]=b}return i};function ue(a,b,c,d,f,g){this.p=a;this.h=b;this.shift=c;this.root=d;this.F=f;this.n=g;this.r=4;this.j=167668511}r=ue.prototype;r.ya=function(){return new ve(this.h,this.shift,we.e?we.e(this.root):we.call(k,this.root),xe.e?xe.e(this.F):xe.call(k,this.F))};r.C=function(a){var b=this.n;return b!=k?b:this.n=a=Cb(a)};r.V=function(a,b){return a.U(a,b,k)};
r.H=function(a,b,c){return a.U(a,b,c)};r.ja=function(a,b,c){var d=0<=b;if(d?b<this.h:d)return ne(a)<=b?(a=this.F.slice(),a[b&31]=c,new ue(this.p,this.h,this.shift,this.root,a,k)):new ue(this.p,this.h,this.shift,te(a,this.shift,this.root,b,c),this.F,k);if(b===this.h)return a.A(a,c);e(Error([E("Index "),E(b),E(" out of bounds  [0,"),E(this.h),E("]")].join("")))};
var ye=k,ye=function(a,b,c){switch(arguments.length){case 2:return this.D(this,b);case 3:return this.U(this,b,c)}e(Error("Invalid arity: "+arguments.length))};r=ue.prototype;r.call=ye;r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};
r.A=function(a,b){if(32>this.h-ne(a)){var c=this.F.slice();c.push(b);return new ue(this.p,this.h+1,this.shift,this.root,c,k)}var d=this.h>>>5>1<<this.shift,c=d?this.shift+5:this.shift;if(d){d=new me(k,Array(32));d.b[0]=this.root;var f=oe(k,this.shift,new me(k,this.F));d.b[1]=f}else d=qe(a,this.shift,this.root,new me(k,this.F));return new ue(this.p,this.h+1,c,d,[b],k)};r.Va=function(a){return a.D(a,0)};r.Wa=function(a){return a.D(a,1)};r.toString=function(){return gb(this)};
r.la=function(a,b){return qb.a(a,b)};r.ma=function(a,b,c){return qb.c(a,b,c)};r.G=function(a){return 0===this.h?k:32>this.h?N.e(this.F):W.c?W.c(a,0,0):W.call(k,a,0,0)};r.L=n("h");r.w=function(a,b){return Eb(a,b)};r.K=function(a,b){return new ue(b,this.h,this.shift,this.root,this.F,this.n)};r.I=n("p");r.D=function(a,b){return re(a,b)[b&31]};r.U=function(a,b,c){var d=0<=b;return(d?b<this.h:d)?a.D(a,b):c};var ze=new me(k,Array(32));
function Y(a){var b=a.length;if(32>b)return new ue(k,b,5,ze,a,k);for(var c=a.slice(0,32),d=32,f=Za(new ue(k,32,5,ze,c,k));;)if(d<b)c=d+1,f=$a(f,a[d]),d=c;else return ab(f)}function sc(a,b,c,d,f,g){this.S=a;this.R=b;this.m=c;this.v=d;this.p=f;this.n=g;this.j=31719660;this.r=1536}r=sc.prototype;r.C=function(a){var b=this.n;return b!=k?b:this.n=a=Cb(a)};r.da=function(a){return this.v+1<this.R.length?(a=W.l?W.l(this.S,this.R,this.m,this.v+1):W.call(k,this.S,this.R,this.m,this.v+1),a==k?k:a):a.Ta(a)};
r.A=function(a,b){return P(b,a)};r.toString=function(){return gb(this)};r.G=ba();r.M=function(){return this.R[this.v]};r.N=function(a){return this.v+1<this.R.length?(a=W.l?W.l(this.S,this.R,this.m,this.v+1):W.call(k,this.S,this.R,this.m,this.v+1),a==k?kb:a):a.xa(a)};r.Ta=function(){var a=this.R.length,a=this.m+a<y(this.S)?W.c?W.c(this.S,this.m+a,0):W.call(k,this.S,this.m+a,0):k;return a==k?k:a};r.w=function(a,b){return Eb(a,b)};
r.K=function(a,b){return W.P?W.P(this.S,this.R,this.m,this.v,b):W.call(k,this.S,this.R,this.m,this.v,b)};r.Ba=function(){return sd.a(this.R,this.v)};r.xa=function(){var a=this.R.length,a=this.m+a<y(this.S)?W.c?W.c(this.S,this.m+a,0):W.call(k,this.S,this.m+a,0):k;return a==k?kb:a};var W,Ae=k;function Be(a,b,c){return new sc(a,re(a,b),b,c,k,k)}function Ce(a,b,c,d){return new sc(a,b,c,d,k,k)}function De(a,b,c,d,f){return new sc(a,b,c,d,f,k)}
Ae=function(a,b,c,d,f){switch(arguments.length){case 3:return Be.call(this,a,b,c);case 4:return Ce.call(this,a,b,c,d);case 5:return De.call(this,a,b,c,d,f)}e(Error("Invalid arity: "+arguments.length))};Ae.c=Be;Ae.l=Ce;Ae.P=De;W=Ae;function we(a){return new me({},a.b.slice())}function xe(a){var b=Array(32);tc(a,0,b,0,a.length);return b}
var Fe=function Ee(b,c,d,f){var d=b.root.q===d.q?d:new me(b.root.q,d.b.slice()),g=b.h-1>>>c&31;if(5===c)b=f;else var i=d.b[g],b=i!=k?Ee(b,c-5,i,f):oe(b.root.q,c-5,f);d.b[g]=b;return d};function ve(a,b,c,d){this.h=a;this.shift=b;this.root=c;this.F=d;this.j=275;this.r=88}var Ge=k,Ge=function(a,b,c){switch(arguments.length){case 2:return this.V(this,b);case 3:return this.H(this,b,c)}e(Error("Invalid arity: "+arguments.length))};r=ve.prototype;r.call=Ge;
r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};r.V=function(a,b){return a.U(a,b,k)};r.H=function(a,b,c){return a.U(a,b,c)};r.D=function(a,b){if(this.root.q)return re(a,b)[b&31];e(Error("nth after persistent!"))};r.U=function(a,b,c){var d=0<=b;return(d?b<this.h:d)?a.D(a,b):c};r.L=function(){if(this.root.q)return this.h;e(Error("count after persistent!"))};
r.na=function(a,b,c){var d;a:{if(a.root.q){var f=0<=b;if(f?b<a.h:f){ne(a)<=b?a.F[b&31]=c:(d=function i(d,f){var p=a.root.q===f.q?f:new me(a.root.q,f.b.slice());if(0===d)p.b[b&31]=c;else{var v=b>>>d&31,x=i(d-5,p.b[v]);p.b[v]=x}return p}.call(k,a.shift,a.root),a.root=d);d=a;break a}if(b===a.h){d=a.ta(a,c);break a}e(Error([E("Index "),E(b),E(" out of bounds for TransientVector of length"),E(a.h)].join("")))}e(Error("assoc! after persistent!"))}return d};
r.ta=function(a,b){if(this.root.q){if(32>this.h-ne(a))this.F[this.h&31]=b;else{var c=new me(this.root.q,this.F),d=Array(32);d[0]=b;this.F=d;if(this.h>>>5>1<<this.shift){var d=Array(32),f=this.shift+5;d[0]=this.root;d[1]=oe(this.root.q,this.shift,c);this.root=new me(this.root.q,d);this.shift=f}else this.root=Fe(a,this.shift,this.root,c)}this.h+=1;return a}e(Error("conj! after persistent!"))};
r.za=function(a){if(this.root.q){this.root.q=k;var a=this.h-ne(a),b=Array(a);tc(this.F,0,b,0,a);return new ue(k,this.h,this.shift,this.root,b,k)}e(Error("persistent! called twice"))};function He(){this.r=0;this.j=2097152}He.prototype.w=q(l);var Ie=new He;function Je(a,b){var c;c=b==k?0:b?((c=b.j&1024)?c:b.pb)||(b.j?0:u(Ca,b)):u(Ca,b);c=c?Rb(a)===Rb(b)?Yd(Zd,$d.a(function(a){return lb.a(Q.c(b,J(a),Ie),J(M(a)))},a)):k:k;return t(c)?h:l}
function Ke(a,b){var c=a.b,d=ea(b);if(d?d:"number"===typeof b)a:{for(var d=c.length,f=0;;){if(d<=f){c=-1;break a}if(b===c[f]){c=f;break a}f+=2}c=aa}else if(b instanceof G)a:{for(var d=c.length,f=b.ia,g=0;;){if(d<=g){c=-1;break a}var i=c[g],j=i instanceof G;if(j?f===i.ia:j){c=g;break a}g+=2}c=aa}else if(b==k)a:{d=c.length;for(f=0;;){if(d<=f){c=-1;break a}if(c[f]==k){c=f;break a}f+=2}c=aa}else a:{d=c.length;for(f=0;;){if(d<=f){c=-1;break a}if(lb.a(b,c[f])){c=f;break a}f+=2}c=aa}return c}
function Le(a,b,c){this.b=a;this.m=b;this.ra=c;this.r=0;this.j=31850702}r=Le.prototype;r.C=function(a){return Cb(a)};r.da=function(){return this.m<this.b.length-2?new Le(this.b,this.m+2,this.ra):k};r.A=function(a,b){return P(b,a)};r.toString=function(){return gb(this)};r.G=ba();r.L=function(){return(this.b.length-this.m)/2};r.M=function(){return Y([this.b[this.m],this.b[this.m+1]])};r.N=function(){return this.m<this.b.length-2?new Le(this.b,this.m+2,this.ra):kb};r.w=function(a,b){return Eb(a,b)};
r.K=function(a,b){return new Le(this.b,this.m,b)};r.I=n("ra");function Me(a,b,c,d){this.p=a;this.h=b;this.b=c;this.n=d;this.r=4;this.j=16123663}r=Me.prototype;r.ya=function(){return new Ne({},this.b.length,this.b.slice())};r.C=function(a){var b=this.n;return b!=k?b:this.n=a=ed(a)};r.V=function(a,b){return a.H(a,b,k)};r.H=function(a,b,c){a=Ke(a,b);return-1===a?c:this.b[a+1]};
r.ja=function(a,b,c){var d=Ke(a,b);if(-1===d){if(this.h<Oe){for(var d=a.b,f=d.length,a=Array(f+2),g=0;;)if(g<f)a[g]=d[g],g+=1;else break;a[f]=b;a[f+1]=c;return new Me(this.p,this.h+1,a,k)}d=La;f=Ba;g=Pe;if(g!=k){var i;if(i=g)i=(i=g.r&4)?i:g.ob;i?(a=Ec.c($a,Za(g),a),a=ab(a)):a=Ec.c(qa,g,a)}else a=Ec.c(Mb,kb,a);return d(f(a,b,c),this.p)}if(c===this.b[d+1])return a;b=this.b.slice();b[d+1]=c;return new Me(this.p,this.h,b,k)};
var Qe=k,Qe=function(a,b,c){switch(arguments.length){case 2:return this.V(this,b);case 3:return this.H(this,b,c)}e(Error("Invalid arity: "+arguments.length))};r=Me.prototype;r.call=Qe;r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};r.A=function(a,b){return pc(b)?a.ja(a,A.a(b,0),A.a(b,1)):Ec.c(qa,a,b)};r.toString=function(){return gb(this)};r.G=function(){return 0<=this.b.length-2?new Le(this.b,0,k):k};r.L=n("h");r.w=function(a,b){return Je(a,b)};
r.K=function(a,b){return new Me(b,this.h,this.b,this.n)};r.I=n("p");var Re=new Me(k,0,[],k),Oe=8;function ma(a){return new Me(k,a.length/2,a,k)}function Ne(a,b,c){this.oa=a;this.ba=b;this.b=c;this.r=56;this.j=258}r=Ne.prototype;r.na=function(a,b,c){if(t(this.oa)){var d=Ke(a,b);if(-1===d){if(this.ba+2<=2*Oe)return this.ba+=2,this.b.push(b),this.b.push(c),a;a=Se.a?Se.a(this.ba,this.b):Se.call(k,this.ba,this.b);return bb(a,b,c)}c!==this.b[d+1]&&(this.b[d+1]=c);return a}e(Error("assoc! after persistent!"))};
r.ta=function(a,b){if(t(this.oa)){var c;c=b?((c=b.j&2048)?c:b.cb)||(b.j?0:u(Da,b)):u(Da,b);if(c)return a.na(a,S.e?S.e(b):S.call(k,b),T.e?T.e(b):T.call(k,b));c=I(b);for(var d=a;;){var f=J(c);if(t(f))c=M(c),d=d.na(d,S.e?S.e(f):S.call(k,f),T.e?T.e(f):T.call(k,f));else return d}}else e(Error("conj! after persistent!"))};r.za=function(){if(t(this.oa))return this.oa=l,new Me(k,Rc((this.ba-this.ba%2)/2),this.b,k);e(Error("persistent! called twice"))};r.V=function(a,b){return a.H(a,b,k)};
r.H=function(a,b,c){if(t(this.oa))return a=Ke(a,b),-1===a?c:this.b[a+1];e(Error("lookup after persistent!"))};r.L=function(){if(t(this.oa))return Rc((this.ba-this.ba%2)/2);e(Error("count after persistent!"))};function Se(a,b){for(var c=Za(Pe),d=0;;)if(d<a)c=bb(c,b[d],b[d+1]),d+=2;else return c}function Te(){this.$=l}function Ue(a,b){return ea(a)?a===b:lb.a(a,b)}var Ve,We=k;function Xe(a,b,c){a=a.slice();a[b]=c;return a}function Ye(a,b,c,d,f){a=a.slice();a[b]=c;a[d]=f;return a}
We=function(a,b,c,d,f){switch(arguments.length){case 3:return Xe.call(this,a,b,c);case 5:return Ye.call(this,a,b,c,d,f)}e(Error("Invalid arity: "+arguments.length))};We.c=Xe;We.P=Ye;Ve=We;var Ze,$e=k;function af(a,b,c,d){a=a.pa(b);a.b[c]=d;return a}function bf(a,b,c,d,f,g){a=a.pa(b);a.b[c]=d;a.b[f]=g;return a}$e=function(a,b,c,d,f,g){switch(arguments.length){case 4:return af.call(this,a,b,c,d);case 6:return bf.call(this,a,b,c,d,f,g)}e(Error("Invalid arity: "+arguments.length))};$e.l=af;$e.T=bf;
Ze=$e;function cf(a,b,c){this.q=a;this.t=b;this.b=c}r=cf.prototype;
r.X=function(a,b,c,d,f,g){var i=1<<(c>>>b&31),j=Sc(this.t&i-1);if(0===(this.t&i)){var m=Sc(this.t);if(2*m<this.b.length){a=this.pa(a);b=a.b;g.$=h;a:{c=2*(m-j);g=2*j+(c-1);for(m=2*(j+1)+(c-1);;){if(0===c)break a;b[m]=b[g];m-=1;c-=1;g-=1}}b[2*j]=d;b[2*j+1]=f;a.t|=i;return a}if(16<=m){j=Array(32);j[c>>>b&31]=df.X(a,b+5,c,d,f,g);for(f=d=0;;)if(32>d)0!==(this.t>>>d&1)&&(j[d]=this.b[f]!=k?df.X(a,b+5,H.e(this.b[f]),this.b[f],this.b[f+1],g):this.b[f+1],f+=2),d+=1;else break;return new ef(a,m+1,j)}b=Array(2*
(m+4));tc(this.b,0,b,0,2*j);b[2*j]=d;b[2*j+1]=f;tc(this.b,2*j,b,2*(j+1),2*(m-j));g.$=h;a=this.pa(a);a.b=b;a.t|=i;return a}m=this.b[2*j];i=this.b[2*j+1];if(m==k)return m=i.X(a,b+5,c,d,f,g),m===i?this:Ze.l(this,a,2*j+1,m);if(Ue(d,m))return f===i?this:Ze.l(this,a,2*j+1,f);g.$=h;return Ze.T(this,a,2*j,k,2*j+1,ff.ka?ff.ka(a,b+5,m,i,c,d,f):ff.call(k,a,b+5,m,i,c,d,f))};r.va=function(){return gf.e?gf.e(this.b):gf.call(k,this.b)};
r.pa=function(a){if(a===this.q)return this;var b=Sc(this.t),c=Array(0>b?4:2*(b+1));tc(this.b,0,c,0,2*b);return new cf(a,this.t,c)};
r.W=function(a,b,c,d,f){var g=1<<(b>>>a&31),i=Sc(this.t&g-1);if(0===(this.t&g)){var j=Sc(this.t);if(16<=j){i=Array(32);i[b>>>a&31]=df.W(a+5,b,c,d,f);for(d=c=0;;)if(32>c)0!==(this.t>>>c&1)&&(i[c]=this.b[d]!=k?df.W(a+5,H.e(this.b[d]),this.b[d],this.b[d+1],f):this.b[d+1],d+=2),c+=1;else break;return new ef(k,j+1,i)}a=Array(2*(j+1));tc(this.b,0,a,0,2*i);a[2*i]=c;a[2*i+1]=d;tc(this.b,2*i,a,2*(i+1),2*(j-i));f.$=h;return new cf(k,this.t|g,a)}j=this.b[2*i];g=this.b[2*i+1];if(j==k)return j=g.W(a+5,b,c,d,f),
j===g?this:new cf(k,this.t,Ve.c(this.b,2*i+1,j));if(Ue(c,j))return d===g?this:new cf(k,this.t,Ve.c(this.b,2*i+1,d));f.$=h;return new cf(k,this.t,Ve.P(this.b,2*i,k,2*i+1,ff.T?ff.T(a+5,j,g,b,c,d):ff.call(k,a+5,j,g,b,c,d)))};r.ha=function(a,b,c,d){var f=1<<(b>>>a&31);if(0===(this.t&f))return d;var g=Sc(this.t&f-1),f=this.b[2*g],g=this.b[2*g+1];return f==k?g.ha(a+5,b,c,d):Ue(c,f)?g:d};var df=new cf(k,0,[]);function ef(a,b,c){this.q=a;this.h=b;this.b=c}r=ef.prototype;
r.X=function(a,b,c,d,f,g){var i=c>>>b&31,j=this.b[i];if(j==k)return a=Ze.l(this,a,i,df.X(a,b+5,c,d,f,g)),a.h+=1,a;b=j.X(a,b+5,c,d,f,g);return b===j?this:Ze.l(this,a,i,b)};r.va=function(){return hf.e?hf.e(this.b):hf.call(k,this.b)};r.pa=function(a){return a===this.q?this:new ef(a,this.h,this.b.slice())};r.W=function(a,b,c,d,f){var g=b>>>a&31,i=this.b[g];if(i==k)return new ef(k,this.h+1,Ve.c(this.b,g,df.W(a+5,b,c,d,f)));a=i.W(a+5,b,c,d,f);return a===i?this:new ef(k,this.h,Ve.c(this.b,g,a))};
r.ha=function(a,b,c,d){var f=this.b[b>>>a&31];return f!=k?f.ha(a+5,b,c,d):d};function jf(a,b,c){for(var b=2*b,d=0;;)if(d<b){if(Ue(c,a[d]))return d;d+=2}else return-1}function kf(a,b,c,d){this.q=a;this.ea=b;this.h=c;this.b=d}r=kf.prototype;
r.X=function(a,b,c,d,f,g){if(c===this.ea){b=jf(this.b,this.h,d);if(-1===b){if(this.b.length>2*this.h)return a=Ze.T(this,a,2*this.h,d,2*this.h+1,f),g.$=h,a.h+=1,a;c=this.b.length;b=Array(c+2);tc(this.b,0,b,0,c);b[c]=d;b[c+1]=f;g.$=h;g=this.h+1;a===this.q?(this.b=b,this.h=g,a=this):a=new kf(this.q,this.ea,g,b);return a}return this.b[b+1]===f?this:Ze.l(this,a,b+1,f)}return(new cf(a,1<<(this.ea>>>b&31),[k,this,k,k])).X(a,b,c,d,f,g)};r.va=function(){return gf.e?gf.e(this.b):gf.call(k,this.b)};
r.pa=function(a){if(a===this.q)return this;var b=Array(2*(this.h+1));tc(this.b,0,b,0,2*this.h);return new kf(a,this.ea,this.h,b)};r.W=function(a,b,c,d,f){return b===this.ea?(a=jf(this.b,this.h,c),-1===a?(a=this.b.length,b=Array(a+2),tc(this.b,0,b,0,a),b[a]=c,b[a+1]=d,f.$=h,new kf(k,this.ea,this.h+1,b)):lb.a(this.b[a],d)?this:new kf(k,this.ea,this.h,Ve.c(this.b,a+1,d))):(new cf(k,1<<(this.ea>>>a&31),[k,this])).W(a,b,c,d,f)};
r.ha=function(a,b,c,d){a=jf(this.b,this.h,c);return 0>a?d:Ue(c,this.b[a])?this.b[a+1]:d};var ff,lf=k;function mf(a,b,c,d,f,g){var i=H.e(b);if(i===d)return new kf(k,i,2,[b,c,f,g]);var j=new Te;return df.W(a,i,b,c,j).W(a,d,f,g,j)}function nf(a,b,c,d,f,g,i){var j=H.e(c);if(j===f)return new kf(k,j,2,[c,d,g,i]);var m=new Te;return df.X(a,b,j,c,d,m).X(a,b,f,g,i,m)}
lf=function(a,b,c,d,f,g,i){switch(arguments.length){case 6:return mf.call(this,a,b,c,d,f,g);case 7:return nf.call(this,a,b,c,d,f,g,i)}e(Error("Invalid arity: "+arguments.length))};lf.T=mf;lf.ka=nf;ff=lf;function of(a,b,c,d,f){this.p=a;this.Y=b;this.m=c;this.Z=d;this.n=f;this.r=0;this.j=31850572}r=of.prototype;r.C=function(a){var b=this.n;return b!=k?b:this.n=a=Cb(a)};r.A=function(a,b){return P(b,a)};r.toString=function(){return gb(this)};r.G=ba();
r.M=function(){return this.Z==k?Y([this.Y[this.m],this.Y[this.m+1]]):J(this.Z)};r.N=function(){return this.Z==k?gf.c?gf.c(this.Y,this.m+2,k):gf.call(k,this.Y,this.m+2,k):gf.c?gf.c(this.Y,this.m,M(this.Z)):gf.call(k,this.Y,this.m,M(this.Z))};r.w=function(a,b){return Eb(a,b)};r.K=function(a,b){return new of(b,this.Y,this.m,this.Z,this.n)};r.I=n("p");var gf,pf=k;function qf(a){return pf.c(a,0,k)}
function rf(a,b,c){if(c==k)for(c=a.length;;)if(b<c){if(a[b]!=k)return new of(k,a,b,k,k);var d=a[b+1];if(t(d)&&(d=d.va(),t(d)))return new of(k,a,b+2,d,k);b+=2}else return k;else return new of(k,a,b,c,k)}pf=function(a,b,c){switch(arguments.length){case 1:return qf.call(this,a);case 3:return rf.call(this,a,b,c)}e(Error("Invalid arity: "+arguments.length))};pf.e=qf;pf.c=rf;gf=pf;function sf(a,b,c,d,f){this.p=a;this.Y=b;this.m=c;this.Z=d;this.n=f;this.r=0;this.j=31850572}r=sf.prototype;
r.C=function(a){var b=this.n;return b!=k?b:this.n=a=Cb(a)};r.A=function(a,b){return P(b,a)};r.toString=function(){return gb(this)};r.G=ba();r.M=function(){return J(this.Z)};r.N=function(){return hf.l?hf.l(k,this.Y,this.m,M(this.Z)):hf.call(k,k,this.Y,this.m,M(this.Z))};r.w=function(a,b){return Eb(a,b)};r.K=function(a,b){return new sf(b,this.Y,this.m,this.Z,this.n)};r.I=n("p");var hf,tf=k;function uf(a){return tf.l(k,a,0,k)}
function vf(a,b,c,d){if(d==k)for(d=b.length;;)if(c<d){var f=b[c];if(t(f)&&(f=f.va(),t(f)))return new sf(a,b,c+1,f,k);c+=1}else return k;else return new sf(a,b,c,d,k)}tf=function(a,b,c,d){switch(arguments.length){case 1:return uf.call(this,a);case 4:return vf.call(this,a,b,c,d)}e(Error("Invalid arity: "+arguments.length))};tf.e=uf;tf.l=vf;hf=tf;function wf(a,b,c,d,f,g){this.p=a;this.h=b;this.root=c;this.O=d;this.Q=f;this.n=g;this.r=4;this.j=16123663}r=wf.prototype;
r.ya=function(){return new xf({},this.root,this.h,this.O,this.Q)};r.C=function(a){var b=this.n;return b!=k?b:this.n=a=ed(a)};r.V=function(a,b){return a.H(a,b,k)};r.H=function(a,b,c){return b==k?this.O?this.Q:c:this.root==k?c:this.root.ha(0,H.e(b),b,c)};
r.ja=function(a,b,c){if(b==k){var d=this.O;return(d?c===this.Q:d)?a:new wf(this.p,this.O?this.h:this.h+1,this.root,h,c,k)}d=new Te;c=(this.root==k?df:this.root).W(0,H.e(b),b,c,d);return c===this.root?a:new wf(this.p,d.$?this.h+1:this.h,c,this.O,this.Q,k)};var yf=k,yf=function(a,b,c){switch(arguments.length){case 2:return this.V(this,b);case 3:return this.H(this,b,c)}e(Error("Invalid arity: "+arguments.length))};r=wf.prototype;r.call=yf;r.apply=function(a,b){a=this;return a.call.apply(a,[a].concat(b.slice()))};
r.A=function(a,b){return pc(b)?a.ja(a,A.a(b,0),A.a(b,1)):Ec.c(qa,a,b)};r.toString=function(){return gb(this)};r.G=function(){if(0<this.h){var a=this.root!=k?this.root.va():k;return this.O?P(Y([k,this.Q]),a):a}return k};r.L=n("h");r.w=function(a,b){return Je(a,b)};r.K=function(a,b){return new wf(b,this.h,this.root,this.O,this.Q,this.n)};r.I=n("p");var Pe=new wf(k,0,k,l,k,0);function xf(a,b,c,d,f){this.q=a;this.root=b;this.count=c;this.O=d;this.Q=f;this.r=56;this.j=258}r=xf.prototype;
r.na=function(a,b,c){return zf(a,b,c)};r.ta=function(a,b){var c;a:{if(a.q){c=b?((c=b.j&2048)?c:b.cb)||(b.j?0:u(Da,b)):u(Da,b);if(c){c=zf(a,S.e?S.e(b):S.call(k,b),T.e?T.e(b):T.call(k,b));break a}c=I(b);for(var d=a;;){var f=J(c);if(t(f))c=M(c),d=zf(d,S.e?S.e(f):S.call(k,f),T.e?T.e(f):T.call(k,f));else{c=d;break a}}}else e(Error("conj! after persistent"));c=aa}return c};r.za=function(a){var b;a.q?(a.q=k,b=new wf(k,a.count,a.root,a.O,a.Q,k)):e(Error("persistent! called twice"));return b};
r.V=function(a,b){return b==k?this.O?this.Q:k:this.root==k?k:this.root.ha(0,H.e(b),b)};r.H=function(a,b,c){return b==k?this.O?this.Q:c:this.root==k?c:this.root.ha(0,H.e(b),b,c)};r.L=function(){if(this.q)return this.count;e(Error("count after persistent!"))};function zf(a,b,c){if(a.q){if(b==k)a.Q!==c&&(a.Q=c),a.O||(a.count+=1,a.O=h);else{var d=new Te,b=(a.root==k?df:a.root).X(a.q,0,H.e(b),b,c,d);b!==a.root&&(a.root=b);d.$&&(a.count+=1)}return a}e(Error("assoc! after persistent!"))}var gc;
function Af(a){for(var b=I(a),c=Za(Pe);;)if(b)var a=M(M(b)),d=J(b),b=J(M(b)),c=bb(c,d,b),b=a;else return ab(c)}function Bf(a){var b=k;0<arguments.length&&(b=N(Array.prototype.slice.call(arguments,0),0));return Af.call(this,b)}Bf.o=0;Bf.k=function(a){a=I(a);return Af(a)};Bf.g=Af;gc=Bf;function S(a){return Ea(a)}function T(a){return Ga(a)}
function Cf(a){var b;if(b=a)b=(b=a.r&4096)?b:a.fb;if(b)return a.name;if(na(a))return a;if(vc(a))return b=a.lastIndexOf("/",a.length-2),0>b?cd.a(a,2):cd.a(a,b+1);e(Error([E("Doesn't support name: "),E(a)].join("")))}function Df(a){var b;if(b=a)b=(b=a.r&4096)?b:a.fb;if(b)return a.qa;if(vc(a))return b=a.lastIndexOf("/",a.length-2),-1<b?cd.c(a,2,b):k;e(Error([E("Doesn't support namespace: "),E(a)].join("")))}
function Z(a,b,c,d,f,g,i){D(a,c);I(i)&&(b.c?b.c(J(i),a,g):b.call(k,J(i),a,g));for(var c=I(M(i)),i=k,j=0,m=0;;)if(m<j){var p=i.D(i,m);D(a,d);b.c?b.c(p,a,g):b.call(k,p,a,g);m+=1}else if(c=I(c))i=c,qc(i)?(c=db(i),m=eb(i),i=c,j=Rb(c),c=m):(c=J(i),D(a,d),b.c?b.c(c,a,g):b.call(k,c,a,g),c=M(i),i=k,j=0),m=0;else break;return D(a,f)}
function Ef(a,b){for(var c=I(b),d=k,f=0,g=0;;)if(g<f){var i=d.D(d,g);D(a,i);g+=1}else if(c=I(c))d=c,qc(d)?(c=db(d),f=eb(d),d=c,i=Rb(c),c=f,f=i):(i=J(d),D(a,i),c=M(d),d=k,f=0),g=0;else return k}function Ff(a,b){var c=k;1<arguments.length&&(c=N(Array.prototype.slice.call(arguments,1),0));return Ef.call(this,a,c)}Ff.o=1;Ff.k=function(a){var b=J(a),a=L(a);return Ef(b,a)};Ff.g=Ef;
var Gf={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"},$=function Hf(b,c,d){if(b==k)return D(c,"nil");if(aa===b)return D(c,"#<undefined>");var f;f=Q.a(d,"\ufdd0:meta");t(f)&&(f=b?((f=b.j&131072)?f:b.eb)?h:b.j?l:u(Ja,b):u(Ja,b),f=t(f)?jc(b):f);t(f)&&(D(c,"^"),Hf(jc(b),c,d),D(c," "));if(b==k)return D(c,"nil");if(b.ib)return b.ub(c);if(f=b)f=(f=b.j&2147483648)?f:b.J;if(f)return b.z(b,c,d);if((f=(b==k?k:b.constructor)===Boolean)?f:"number"===typeof b)return D(c,""+E(b));
if(b instanceof Array)return Z(c,Hf,"#<Array [",", ","]>",d,b);if(ea(b))return vc(b)?(D(c,":"),d=Df(b),t(d)&&Ff.g(c,N([""+E(d),"/"],0)),D(c,Cf(b))):b instanceof G?(d=Df(b),t(d)&&Ff.g(c,N([""+E(d),"/"],0)),D(c,Cf(b))):t((new kd("\ufdd0:readably")).call(k,d))?D(c,[E('"'),E(b.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(b){return Gf[b]})),E('"')].join("")):D(c,b);if((f="function"==s(b))?f:b?t(t(k)?k:b.mb)||(b.wb?0:u(oa,b)):u(oa,b))return Ff.g(c,N(["#<",""+E(b),">"],0));if(b instanceof Date)return d=
function(b,c){for(var d=""+E(b);;)if(Rb(d)<c)d=[E("0"),E(d)].join("");else return d},Ff.g(c,N(['#inst "',""+E(b.getUTCFullYear()),"-",d(b.getUTCMonth()+1,2),"-",d(b.getUTCDate(),2),"T",d(b.getUTCHours(),2),":",d(b.getUTCMinutes(),2),":",d(b.getUTCSeconds(),2),".",d(b.getUTCMilliseconds(),3),"-",'00:00"'],0));t(b instanceof RegExp)?b=Ff.g(c,N(['#"',b.source,'"'],0)):(f=b?((f=b.j&2147483648)?f:b.J)||(b.j?0:u(Wa,b)):u(Wa,b),b=f?Xa(b,c,d):Ff.g(c,N(["#<",""+E(b),">"],0)));return b};
function If(a){var b=ka(),c=a==k;c||(c=I(a),c=t(c)?l:h);if(c)b="";else{var c=E,d=new ja,f=new fb(d);a:{$(J(a),f,b);for(var a=I(M(a)),g=k,i=0,j=0;;)if(j<i){var m=g.D(g,j);D(f," ");$(m,f,b);j+=1}else if(a=I(a))g=a,qc(g)?(a=db(g),i=eb(g),g=a,m=Rb(a),a=i,i=m):(m=J(g),D(f," "),$(m,f,b),a=M(g),g=k,i=0),j=0;else break a}Va(f);b=""+c(d)}return b}function Jf(a){var b=k;0<arguments.length&&(b=N(Array.prototype.slice.call(arguments,0),0));return If(b)}Jf.o=0;Jf.k=function(a){a=I(a);return If(a)};Jf.g=function(a){return If(a)};
jb.prototype.J=h;jb.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};rc.prototype.J=h;rc.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};Me.prototype.J=h;Me.prototype.z=function(a,b,c){return Z(b,function(a){return Z(b,$,""," ","",c,a)},"{",", ","}",c,a)};od.prototype.J=h;od.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};of.prototype.J=h;of.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};sc.prototype.J=h;
sc.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};wf.prototype.J=h;wf.prototype.z=function(a,b,c){return Z(b,function(a){return Z(b,$,""," ","",c,a)},"{",", ","}",c,a)};ue.prototype.J=h;ue.prototype.z=function(a,b,c){return Z(b,$,"["," ","]",c,a)};fd.prototype.J=h;fd.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};Le.prototype.J=h;Le.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};gd.prototype.J=h;gd.prototype.z=function(a,b){return D(b,"()")};jd.prototype.J=h;
jd.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};sf.prototype.J=h;sf.prototype.z=function(a,b,c){return Z(b,$,"("," ",")",c,a)};ue.prototype.$a=h;ue.prototype.ab=function(a,b){return xc.a(a,b)};function Kf(a,b,c,d){this.state=a;this.p=b;this.kb=c;this.lb=d;this.j=2153938944;this.r=2}r=Kf.prototype;r.C=function(a){return a[fa]||(a[fa]=++ga)};
r.Xa=function(a,b,c){for(var d=I(this.lb),f=k,g=0,i=0;;)if(i<g){var j=f.D(f,i),m=Wb.c(j,0,k),j=Wb.c(j,1,k);j.l?j.l(m,a,b,c):j.call(k,m,a,b,c);i+=1}else if(d=I(d))qc(d)?(f=db(d),d=eb(d),m=f,g=Rb(f),f=m):(f=J(d),m=Wb.c(f,0,k),j=Wb.c(f,1,k),j.l?j.l(m,a,b,c):j.call(k,m,a,b,c),d=M(d),f=k,g=0),i=0;else return k};r.z=function(a,b,c){D(b,"#<Atom: ");$(this.state,b,c);return D(b,">")};r.I=n("p");r.bb=n("state");r.w=function(a,b){return a===b};var Lf,Mf=k;function Nf(a){return new Kf(a,k,k,k)}
function Of(a,b){var c=uc(b)?Qd.a(gc,b):b,d=Q.a(c,"\ufdd0:validator"),c=Q.a(c,"\ufdd0:meta");return new Kf(a,c,d,k)}function Pf(a,b){var c=k;1<arguments.length&&(c=N(Array.prototype.slice.call(arguments,1),0));return Of.call(this,a,c)}Pf.o=1;Pf.k=function(a){var b=J(a),a=L(a);return Of(b,a)};Pf.g=Of;Mf=function(a,b){switch(arguments.length){case 1:return Nf.call(this,a);default:return Pf.g(a,N(arguments,1))}e(Error("Invalid arity: "+arguments.length))};Mf.o=1;Mf.k=Pf.k;Mf.e=Nf;Mf.g=Pf.g;Lf=Mf;
function Qf(a,b){var c=a.kb;t(c)&&!t(c.e?c.e(b):c.call(k,b))&&e(Error([E("Assert failed: "),E("Validator rejected reference state"),E("\n"),E(Jf.g(N([Db(new G(k,"validate","validate",1233162959,k),new G(k,"new-value","new-value",972165309,k))],0)))].join("")));c=a.state;a.state=b;Ya(a,c,b);return b}var Rf,Sf=k;function Tf(a,b){return Qf(a,b.e?b.e(a.state):b.call(k,a.state))}function Uf(a,b,c){return Qf(a,b.a?b.a(a.state,c):b.call(k,a.state,c))}
function Vf(a,b,c,d){return Qf(a,b.c?b.c(a.state,c,d):b.call(k,a.state,c,d))}function Wf(a,b,c,d,f){return Qf(a,b.l?b.l(a.state,c,d,f):b.call(k,a.state,c,d,f))}function Xf(a,b,c,d,f,g){return Qf(a,Qd.g(b,a.state,c,d,f,N([g],0)))}function Yf(a,b,c,d,f,g){var i=k;5<arguments.length&&(i=N(Array.prototype.slice.call(arguments,5),0));return Xf.call(this,a,b,c,d,f,i)}Yf.o=5;Yf.k=function(a){var b=J(a),a=M(a),c=J(a),a=M(a),d=J(a),a=M(a),f=J(a),a=M(a),g=J(a),a=L(a);return Xf(b,c,d,f,g,a)};Yf.g=Xf;
Sf=function(a,b,c,d,f,g){switch(arguments.length){case 2:return Tf.call(this,a,b);case 3:return Uf.call(this,a,b,c);case 4:return Vf.call(this,a,b,c,d);case 5:return Wf.call(this,a,b,c,d,f);default:return Yf.g(a,b,c,d,f,N(arguments,5))}e(Error("Invalid arity: "+arguments.length))};Sf.o=5;Sf.k=Yf.k;Sf.a=Tf;Sf.c=Uf;Sf.l=Vf;Sf.P=Wf;Sf.g=Yf.g;Rf=Sf;function Zf(a,b){a.connect(b);return b}
function $f(a,b){var c=fe.l(b,Y(["\ufdd0:duration"]),Nc,1.5),d=uc(c)?Qd.a(gc,c):c,f=Q.a(d,"\ufdd0:duration"),g=Q.a(d,"\ufdd0:delay"),i=Q.a(d,"\ufdd0:cent"),d=a.createOscillator();d.frequency.value=440;d.detune.value=i-900;d.noteOn(g);d.noteOff(g+f);var g=uc(c)?Qd.a(gc,c):c,c=Q.a(g,"\ufdd0:duration"),f=Q.a(g,"\ufdd0:delay"),g=Q.a(g,"\ufdd0:volume"),i=a.createGainNode(),j=i.gain;j.linearRmpToValueAtTime(0,f);j.linearRmpToValueAtTime(g,f+0.05);j.linearRmpToValueAtTime(0,f+c);return Zf(d,i)}
function ag(a){return new a}var bg=Lf.e(Re);function cg(a){var b=Q.a(Ia(bg),a);if(t(b))return b;b=Qd.a(ag,a);Rf.l(bg,dc,a,b);return b}function dg(a){var b=k;0<arguments.length&&(b=N(Array.prototype.slice.call(arguments,0),0));return cg.call(this,b)}dg.o=0;dg.k=function(a){a=I(a);return cg(a)};dg.g=cg;
function eg(a,b){var c;c=window.AudioContext;c=t(c)?c:window.webkitAudioContext;if(t(c)){c=dg.e?dg.e(c):dg.call(k,c);for(var d=c.createDynamicsCompressor(),f=c.currentTime,g=I(b),i=k,j=0,m=0;;)if(m<j){var p=i.D(i,m);Zf(a.a?a.a(c,fe.l(p,Y(["\ufdd0:delay"]),Jc,f)):a.call(k,c,fe.l(p,Y(["\ufdd0:delay"]),Jc,f)),d);m+=1}else if(g=I(g))i=g,qc(i)?(g=db(i),m=eb(i),i=g,j=Rb(g),g=m):(g=J(i),Zf(a.a?a.a(c,fe.l(g,Y(["\ufdd0:delay"]),Jc,f)):a.call(k,c,fe.l(g,Y(["\ufdd0:delay"]),Jc,f)),d),g=M(i),i=k,j=0),m=0;else break;
return Zf(d,c.destination)}return alert("sorry, this browser doesn't support audio context")}eg($f,Y([ma(["\ufdd0:cent",1100,"\ufdd0:duration",1,"\ufdd0:delay",0,"\ufdd0:volume",0.6]),ma(["\ufdd0:cent",1400,"\ufdd0:duration",1,"\ufdd0:delay",0.2,"\ufdd0:volume",0.6]),ma(["\ufdd0:cent",1800,"\ufdd0:duration",1,"\ufdd0:delay",0.4,"\ufdd0:volume",0.6])]));
da("joy.music.go",function(){return eg($f,Cd.g(Y([Y([11,2]),Y([16,3]),Y([19,1]),Y([18,2]),Y([16,4]),Y([23,2])]),Y([Y([21,6]),Y([18,6]),Y([16,3]),Y([19,1]),Y([18,2]),Y([14,4]),Y([17,2]),Y([11,10])]),N([Y([Y([11,2]),Y([16,3]),Y([19,1]),Y([18,2]),Y([16,4]),Y([23,2])]),Y([Y([26,4]),Y([25,2]),Y([24,4]),Y([20,2]),Y([24,3]),Y([23,1]),Y([22,2]),Y([10,4]),Y([19,2]),Y([16,10])])],0)))});